/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmsession_free: (a: number, b: number) => void;
export const infer: (a: number, b: number, c: number, d: number, e: number) => number;
export const init: () => void;
export const isModelLoaded: () => number;
export const loadModel: (a: number, b: number, c: number, d: number) => number;
export const loadModelForceReload: (a: number, b: number, c: number, d: number, e: number) => number;
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const __wbg_phonemizer_free: (a: number, b: number) => void;
export const get_list_size: () => number;
export const get_rules_size: () => number;
export const phonemizer_get_error: (a: number, b: number) => void;
export const phonemizer_is_loaded: (a: number) => number;
export const phonemizer_new: (a: number) => void;
export const phonemizer_new_with_custom: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const phonemizer_phonemize_text: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_518: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_715: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_533: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_533_1: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_720: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1703: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
