name: Build & Deploy

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-unknown-unknown
      
    - name: Install rust-just
      run: npm install -g rust-just

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Install wasm-opt
      run: npm install -g wasm-opt

    - name: Build WASM
      run: just build-release

    - name: Test phonemizer/tokenizer (won't fail ever)
      run: just test
            
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: wasm-build
        path: pkg/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:   
    - name: TBD
      run:
        echo "TBD"
    
 
