// generated by Opus ... might be a bit over-engineered
// I don't have enough knowledge of audio formats to do this myself
// but it works so that's what matters
/**
 * Encode raw f32 PCM samples into a WAV file blob.
 *
 * @param {Float32Array} samples  PCM samples in -1..1 range
 * @param {number}       sampleRate  e.g. 24000
 * @param {number}       numChannels 1 = mono
 * @returns {Blob}       audio/wav blob
 */
export function encodeWav(samples, sampleRate = 24000, numChannels = 1) {
    const bitsPerSample = 16;
    const bytesPerSample = bitsPerSample / 8;
    const blockAlign = numChannels * bytesPerSample;
    const dataBytes = samples.length * bytesPerSample;
    const headerBytes = 44;
    const buffer = new ArrayBuffer(headerBytes + dataBytes);
    const view = new DataView(buffer);

    /* ---- RIFF header ---- */
    writeString(view, 0, 'RIFF');
    view.setUint32(4, 36 + dataBytes, true);       // file size - 8
    writeString(view, 8, 'WAVE');

    /* ---- fmt  sub-chunk ---- */
    writeString(view, 12, 'fmt ');
    view.setUint32(16, 16, true);                   // sub-chunk size (PCM = 16)
    view.setUint16(20, 1, true);                    // audio format (1 = PCM)
    view.setUint16(22, numChannels, true);
    view.setUint32(24, sampleRate, true);
    view.setUint32(28, sampleRate * blockAlign, true); // byte rate
    view.setUint16(32, blockAlign, true);
    view.setUint16(34, bitsPerSample, true);

    /* ---- data sub-chunk ---- */
    writeString(view, 36, 'data');
    view.setUint32(40, dataBytes, true);

    /* ---- PCM samples: f32 → int16 with clamping ---- */
    let offset = headerBytes;
    for (let i = 0; i < samples.length; i++) {
        const s = Math.max(-1, Math.min(1, samples[i]));
        view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7FFF, true);
        offset += 2;
    }

    return new Blob([buffer], { type: 'audio/wav' });
}

function writeString(view, offset, str) {
    for (let i = 0; i < str.length; i++) {
        view.setUint8(offset + i, str.charCodeAt(i));
    }
}
